language: go

sudo: false

go:
  - 1.8

install:
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get ./...

script:
  - go test ./...
  - go test -race -run=xxx -test.bench=. -test.benchmem=true ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
